services:
  backend:
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    entrypoint:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]

  frontend:
    build:
      target: build # w dev pomijamy etap nginx, chcemy Node z hot-reloadem
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
