"""changed column names to polish and status as enum

Revision ID: 3b16af19f39b
Revises: 6d42fa2ea67a
Create Date: 2026-07-06 15:38:18.537413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b16af19f39b'
down_revision: Union[str, Sequence[str], None] = '6d42fa2ea67a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main_category', sa.String(), nullable=False),
    sa.Column('risk_type', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='riskstatus'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('zagrozenia')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zagrozenia',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('kategoria_glowna', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('typ_ryzyka', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('waga', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('zrodlo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('data_aktualizacji', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('zagrozenia_pkey'))
    )
    op.drop_table('risks')
    # ### end Alembic commands ###
