"""utworzenie tabeli zagrozenia

Revision ID: 6d42fa2ea67a
Revises: 
Create Date: 2026-07-06 11:27:17.353487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d42fa2ea67a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zagrozenia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kategoria_glowna', sa.String(), nullable=False),
    sa.Column('typ_ryzyka', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('waga', sa.Integer(), nullable=True),
    sa.Column('zrodlo', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('data_aktualizacji', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zagrozenia')
    # ### end Alembic commands ###
