"""add address column

Revision ID: d5b9a420b304
Revises: 9d253ef6b775
Create Date: 2026-07-07 14:19:56.664387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5b9a420b304'
down_revision: Union[str, Sequence[str], None] = '9d253ef6b775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risks', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risks', 'address')
    # ### end Alembic commands ###
